name: Build and Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: cargo test --all-features
    - name: Format
      run: cargo fmt --check